version: '3.8'
services:
  backend:
    build:
      context: ./backend
    image: k8svision-backend:latest
    container_name: k8svision-backend
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./backend/config.yaml:/app/config.yaml:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: k8svision-frontend:latest
    container_name: k8svision-frontend
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped 