version: '3.8'
services:
  backend:
    build:
      context: ./backend
    image: k8svision-backend:latest
    container_name: k8svision-backend
    environment:
      - SERVER_PORT=8080
      - CONFIG_PATH=/app/config.yaml
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: k8svision-frontend:latest
    container_name: k8svision-frontend
    environment:
      - VITE_API_URL=/api
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped 