version: '3.8'
services:
  backend:
    image: ghcr.io/nick0323/vision-backend:latest
    container_name: vision-backend
    environment:
      - TZ=Asia/Shanghai
      - KUBECONFIG=/app/config.yaml
      - LOGIN_USERNAME=admin
      - LOGIN_PASSWORD=12345678
      - GIN_MODE=release
      - LOGIN_MAX_FAIL=3
      - LOGIN_LOCK_MINUTES=5
    volumes:
      - ~/.kube/config:/app/config.yaml:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: ghcr.io/nick0323/vision-frontend:latest
    container_name: vision-frontend
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped